GameHopper/Models/Tag.cs
namespace GameHopper.Models
{
    public class Tag
    {
        public int Id { get; set; }

        public string? Name { get; set; }

        public ICollection<Game>? Games { get; set; } = new List<Game>();
        public ICollection<Piece>? Pieces { get; set; }
        public ICollection<Category>? Categories { get; set; } = new List<Category>();
        public Tag(string name)
        {
            Name = name;
        }

        public Tag()
        {
        } 

        public override string ToString()
        {
            return Name;
        }

    }
}

GameHopper/Models/Tags.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GameHopper.Models
{
    public class Tag
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public ICollection<Game> LinkedGames { get; set; }
        public ICollection<Category> Categories { get; set; }


        [Required(ErrorMessage = "Tag name is required")]
        [StringLength(25, MinimumLength = 2, ErrorMessage = "Tag name must be between 2 and 25 characters")]
        public string TagName { get; set; }

        public ICollection<Tag>? Tags { get; set; }

        public Tag(string name)
        {
            TagName = name;
            Tags = new List<Tag>();
        }

        public Tag()
        {
        }

        public override string ToString()
        {
            return Name;
        }

        public override bool Equals(object? obj)
        {
            return obj is Tag @tag &&
                    Id == @tag.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

GameHopper/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using GameHopper.Models;
using GameHopper.ViewModels;


namespace GameHopper.Controllers
{
    public class TagController : Controller
    {
        private GameDbContext context;

        public TagController(GameDbContext dbContext)
        {
            context = dbContext;
        }
        public IActionResult Index()
        {
            List<Tag> tags = context.Tags.ToList();
            return View(tags);
        }


        [HttpGet]
        public IActionResult Add()
        {
            AddTagViewModel addTagViewModel = new AddTagViewModel();
            return View(addTagViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddTagViewModel addTagViewModel)
        {
            if (ModelState.IsValid)
            
            {
        
                Tag newTag = new Tag
                {
                    Name = addTagViewModel.TagName,
                    Id = addTagViewModel.Id
                };

                bool tags = context.Tags.Any(x => x.Name == newTag.Name);


                    if (tags)
                    {

                        return Redirect("/Tag/Add/");
                        
                    }

                    else
                    {

                    context.Tags.Add(newTag);
                    context.SaveChanges();
                    return Redirect("/Tag/");
                    }
                }
                return View("Add", addTagViewModel);
            }
          
          public IActionResult Delete()
        {
            ViewBag.tags = context.Tags.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] tagIds)
        {
            foreach (int tagId in tagIds)
            {
                Tag theTag = context.Tags.Find(tagId);
                context.Tags.Remove(theTag);
            }

            context.SaveChanges();

            return Redirect("/Tag/");
        }

        public IActionResult Edit()
        {
            ViewBag.tags = context.Tags.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Edit(int[] tagIds, AddTagViewModel addTagViewModel)
        {
            foreach (int tagId in tagIds)
            {
                Tag oldTag = context.Tags.Find(tagId);

                Tag newTag = new Tag
                {
                    Name = addTagViewModel.TagName,
                    Id = tagId
                };
                bool tags = context.Tags.Any(x => x.Name == newTag.Name);


                    if (tags)
                    {

                        return Redirect("/Tag/Edit/");
                        
                    }

                    else
                    {

                context.Tags.Remove(oldTag);
                context.Tags.Add(newTag);
                    }
                    context.SaveChanges();
            }


            return Redirect("/Tag/");
        }
            
        }
        
    }

GameHopper/Views/Tag/Add.cshtml
@using GameHopper.Models;
@model GameHopper.ViewModels.AddTagViewModel
@{
    ViewData["Title"] = "Create Tag";
    }

 <h5 class="mb-4">Create New Tag</h5>

<div>

<form asp-controller="Tag" asp-action="Add" method="post">

    <div class="form-group">
        <label asp-for="TagName">Tag: </label>
        <input asp-for="TagName" />
        <span asp-validation-for="TagName"></span>
    </div>

    <br />

    <input type="submit" value="Add new tag" />

</form>

GameHopper/Views/Tag/Delete.cshtml
<h1>Delete Tag</h1>

<form method="post">
    @foreach (var tag in ViewBag.tags)
    {
        <div>
            <label>
                <span>@tag.Name</span>
                <input type="checkbox" name="tagIds" value="@tag.Id">
            </label>
        </div>
    }

    <input type="submit" value="Delete Selected Tags" class="btn btn-danger">

</form>

GameHopper/Views/Tag/Edit.cshtml
@using GameHopper.Models;
@model GameHopper.ViewModels.AddTagViewModel

<h1>Edit a Tag</h1>

<form method="post">
    @foreach (var tag in ViewBag.tags)
    {
        <div>
            <label>
                <span>@tag.Name</span>
                <input type="radio" name="tagIds" value="@tag.Id">
            </label>
        </div>
    }

    <form asp-controller="Tag" asp-action="Add" method="post">

    <div class="form-group">
        <label asp-for="TagName">New Tag Name: </label>
        <input asp-for="TagName" />
        <span asp-validation-for="TagName"></span>
    </div>

    <br />

    <input type="submit" value="Edit Selected Tag" class="btn btn-danger">

</form>

</form>

GameHopper/Views/Tag/Index.cshtml
@using GameHopper.Models;
@model List<GameHopper.Models.Tag>

@{
    ViewData["Title"] = "Tag";
    }


    <h1>All Tags</h1>

    <table class="table">
        <tr>
            <th>Id
            <th>Name</th>
        </tr>
        @foreach (Tag tag in @Model)
        {
            <tr>
                <td>@tag.Id</td>
                <td>@tag.Name</td>
            </tr>
        }
    </table>

<p><a asp-controller="Tag" asp-action="Add">Add more tags</a></p>
<p><a asp-controller="Tag" asp-action="Edit">Edit a tag</a></p>
<p><a asp-controller="Tag" asp-action="Delete">Delete Tag</a></p>